### ISSUE TITLE
I meeting a Problem

### ISSUE THREAD

**Issue by feveruncle7** [zishun/geodesic_matlab#2]
Sir or Madam:
     At first, thanks for your effort.
     Well I met a problem when using your code. Honestly I am not a skillful programmer. I only make some basic appliction.  I intalled MATLAB 2016b and VS2013, I downloaded your code, and I followed your advice:
       1.Build projects example0 and example1 in geodesic.sln.
       2.Copy built library geodesic.dll  to the folder matlab.
then  I run example1in Matlab. But the matlab shows 

       >> example1
       错误使用 loadlibrary
       加载库 "geodesic_debug.dll" 时出错
       找不到指定的模块。
       出错 geodesic_new_mesh (line 7)
        loadlibrary([geodesic_library '.dll'], hfile);
       出错 example1 (line 13)
       mesh = geodesic_new_mesh(vertices,faces);         %initilize new mesh
       原因:
           错误使用 loaddefinedlibrary
           找不到指定的模块。   

 I don know whats wrong? 
btw, My email address is 1317391959@qq.com，waiting for you reply, thank you

**Comment by zishun** [comment]
Hi @feveruncle7! The short answer is: please copy ```geodesic.dll``` to the folder ```matlab``` and rename it as ``` geodesic_debug.dll```.

Also you can try the [update version](https://github.com/zishun/geodesic_matlab/tree/24a391a8bd9abeeb665e28ab7593fd113aa5dbf8), which will generate ```geodesic_debug.dll``` or ```geodesic_release.dll``` directly. What I have done is to replace ```$(ProjectName)``` with ```$(ProjectName)_$(Configuration.toLower())``` in ```geodesic Project Properties -> Configuration Properties -> General -> Target Name```
![Capture](https://user-images.githubusercontent.com/14616133/63974382-a39e0400-caa4-11e9-8377-ea4eda6782dd.PNG)

**Comment by feveruncle7** [comment]
It **works**! Thank you

**Comment by zishun** [comment]
@feveruncle7 That's great! I will close this issue. Would you like to star this repository if you find it helpful? Thus other people can easily see it.
