### ISSUE TITLE
I can do nothing!

### ISSUE THREAD

**Issue by westail** [zishun/geodesic_matlab#4]
Error  geodesic_new_mesh (line 7)
         loadlibrary([geodesic_library '.dll'], hfile);
when run  "example1.m"

and please tell me how to do this:
{
Build
Windows + MSVC
C++ executable

Build projects example0 and example1 in geodesic.sln.
MATLAB API functions

Build project geodesic in geodesic.sln.
Copy built library geodesic_(debug|release).dll to the folder matlab.
Run example[1-5] in Matlab.
}

**Comment by zishun** [comment]
Please download ```geodesic_matlab-v1.0.zip``` at <https://github.com/zishun/geodesic_matlab/releases/tag/v1.0>, unzip and then run ```example1.m``` inside.
