### ISSUE TITLE
The error still exists

### ISSUE THREAD

**Issue by westail** [zishun/geodesic_matlab#5]
I did what you said, but there were still mistakes.
{
索引超出矩阵维度。

出错 loadlibrary>getLoadlibraryCompilerConfiguration (line 520)

出错 loadlibrary (line 263)

出错 geodesic_new_mesh (line 7)
        loadlibrary([geodesic_library '.dll'], hfile);

出错 example1 (line 13)
mesh = geodesic_new_mesh(vertices,faces);         %initilize new mesh
}

**Comment by westail** [comment]
This time, I can run it in 2019b, but there are holes in several stereograms. I don't quite understand if it's the algorithm itself?

**Comment by zishun** [comment]
Can you reproduce the result of ```example1.m```? If so, It is highly possible that there is nothing wrong with the source code in this repository. If you do think that is the problem of the code here (think twice, <https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way>), please provide more information, such as your input.
