### ISSUE TITLE
geodesic_new_mesh causes segmentation fault for some meshes

### ISSUE THREAD

**Issue by p-j-smith** [zishun/geodesic_matlab#6]
Hi, thank you for creating `geodesic_matlab`!

For some inputs, `geodesic_new_mesh` causes a segmentation fault. This issue occurs on line 32, where the library is called:
```mat
[id, tmp1, tmp2, num_edges, edges] = calllib(geodesic_library, 'new_mesh', length(p)/3, p, length(t)/3, t, 1, tmp);
```

To reproduce:
```
load points.mat
load tri.mat
geodesic_new_mesh(points, tri)
```

I've included `points.mat`, `tri.mat`, and the crash report in [new_mesh_crashes.zip](https://github.com/zishun/geodesic_matlab/files/7889357/new_mesh_crashes.zip)

Any suggestions would be much appreciated!

**Comment by zishun** [comment]
Hi! I think the problem is the mesh is not manifold, as shown in the red circle.
![Screenshot from 2022-01-19 20-18-20](https://user-images.githubusercontent.com/14616133/150128578-295ec0af-7718-47a8-a1ea-a6b2a89cd142.png)

**Comment by p-j-smith** [comment]
Ah, that makes sense, thank you so much for your fast response :)
